server:
  port: 8761

eureka:
  instance:
    hostname: eureka8761
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka8762:8762/eureka/,http://eureka8763:8763/eureka/